name: floating_lyric
description: A new Flutter project.

publish_to: "none"

version: 3.6.0+19

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^8.1.2
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.3.2
  introduction_screen: ^3.1.14
  lottie: ^3.1.2
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  logger: ^2.4.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  in_app_review: ^2.0.9
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.7
  http: ^1.2.2
  package_info_plus: ^8.0.2
  flutter_overlay_window: ^0.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  freezed: ^2.3.2
  custom_lint: ^0.5.8
  riverpod_lint: ^2.1.1
  json_serializable: ^6.6.1
  isar_generator: ^3.0.5
  riverpod_generator: ^2.3.3
  analyzer: 5.13.0
  flutter_gen_runner: ^5.7.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/launcher_icon/icons8-songs-and-lyrics-on-the-music-application-72.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
