name: floating_lyric
description: A new Flutter project.

publish_to: "none"

version: 3.3.2+14

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^6.1.1
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.2.2
  introduction_screen: ^3.1.12
  lottie: ^3.0.0
  feature_discovery: ^0.14.1
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  flutter_easylogger: ^2.3.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  url_launcher: ^6.2.4
  auto_size_text: ^3.0.0
  path_provider: ^2.1.2
  in_app_review: ^2.0.8
  riverpod_annotation: ^2.3.3
  go_router: ^13.0.1
  http: ^1.2.0
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner:
  hive_generator: ^2.0.0
  freezed: ^2.3.2
  custom_lint: ^0.5.8
  riverpod_lint: ^2.1.1
  json_serializable: ^6.6.1
  isar_generator: ^3.0.5
  riverpod_generator:
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/launcher_icon/icons8-songs-and-lyrics-on-the-music-application-72.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
