name: floating_lyric
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  system_alert_window: ^1.2.1
  file_picker: ^5.2.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.0.18
  permission_handler: ^10.2.0
  introduction_screen: ^3.1.7
  lottie: ^2.3.0
  feature_discovery: ^0.14.1
  flutter_riverpod: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: any
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  freezed: ^2.3.2
  custom_lint: ^0.3.2
  riverpod_lint: ^1.1.6
  json_serializable: ^6.6.1

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/launcher_icon/icons8-songs-and-lyrics-on-the-music-application-72.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
