name: floating_lyric
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  system_alert_window: ^1.1.2
  file_picker: ^5.2.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_colorpicker: ^1.0.3
  get: ^4.6.5
  shared_preferences: ^2.0.15
  permission_handler: ^10.0.0
  flutter_local_notifications: ^11.0.1
  introduction_screen: ^3.0.2
  lottie: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/launcher_icon/icons8-songs-and-lyrics-on-the-music-application-72.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
