name: floating_lyric
description: A new Flutter project.

publish_to: "none"

version: 2.1.3+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^5.2.7
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.1.0
  introduction_screen: ^3.1.7
  lottie: ^2.3.2
  feature_discovery: ^0.14.1
  flutter_riverpod: ^2.3.3
  freezed_annotation: ^2.2.0
  flutter_easylogger: ^2.3.3
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  url_launcher: ^6.1.10
  auto_size_text: ^3.0.0
  path_provider: ^2.0.15
  in_app_review: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: any
  hive_generator: ^2.0.0
  freezed: ^2.3.2
  custom_lint: ^0.4.0
  riverpod_lint: ^1.1.7
  json_serializable: ^6.6.1
  isar_generator: ^3.0.5
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/launcher_icon/icons8-songs-and-lyrics-on-the-music-application-72.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
